"""add column count for the product

Revision ID: 0a66d52267b1
Revises: 86e722991e96
Create Date: 2025-09-25 16:26:35.280248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a66d52267b1'
down_revision: Union[str, Sequence[str], None] = '86e722991e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('count', sa.Integer(), nullable=True))
    op.alter_column('users', 'balance',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('product', 'count')
    # ### end Alembic commands ###
