services:
  db:
    image: postgres:17-alpine
    container_name: shop_db
    env_file:
      - .env-non-dev

  redis:
    image: redis:7
    container_name: shop_redis

  shop:
    image: shop_images
    build:
      context: .
    container_name: shop_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    ports:
      - "9000:8000"
    command: gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000

  celery:
    image: celery_images
    build:
      context: .
    container_name: shop_celery
    depends_on:
      - redis
    command: celery -A app.tasks.celery_app:celery worker --loglevel=INFO


  flower:
    image: mher/flower
    container_name: shop_flower
    depends_on:
      - redis
    env_file:
      - .env-non-dev
    ports:
      - "5555:5555"
    command: [ "--broker=redis://redis:6379/0", "--port=5555" ]
